### ISSUE TITLE
NordVPN compatibility?

### ISSUE THREAD

**Issue by john27rg** [LeelaChessZero/lczero-client#109]
Hi, I've just installed this and am a complete newbie to Github etc. (Chemical engineer not a programmer.)
When I run Client.exe (on Windows 10) I initially got this message:
GPU compute capability: 6.1 _so everything installed ok_
Error talking to server: Server gave back empty SHA _this message repeated a few times_

When I turned off NordVPN, suspecting this was a VPN caused issue, sure enoughit all seemed to start running.
Is there some way of setting this up so it runs behind NordVPN?

**Comment by mooskagh** [comment]
I've just checked with IVPN and it works fine.
It may happen that Cloudflare doesn't like NordVPN, or NordVPN doesn't support uploads of files of few megabytes in size.

**Comment by john27rg** [comment]
Thanks. Perhaps I just needed a restart. You're right it works now.
