### ISSUE TITLE
ConvertMovesToPGN should claim 50 move and 3 fold draws

### ISSUE THREAD

**Issue by Tilps** [LeelaChessZero/lczero-client#33]
https://github.com/LeelaChessZero/lczero-client/blob/release/lc0_main.go#L186 - somewhere about here.

Otherwise 3 fold and 50 move drawn games are showing up in pgn format as incomplete - which is confusing with all of the resigns.

**Comment by borg323** [comment]
Is there a reason to avoid using encodePGN  from the chess package?

**Comment by Hungry-Caterpillar** [comment]
The result from lc0 for selfplay/training games is never used so all games unless they are mate (#) are all marked as incomplete.
I have done some updates to grab the result and also use the chess.PGN() which correctly identifies the game Outcome and can identify threefold repetition (once its happened). I will play around a little with comments to see what info I could place at the end of the game - very little is coming from lc0.

As a newbie I don't know how to submit any changes via github although I could also paste the code here.

**Comment by Tilps** [comment]
I think this is done now...

Resigns are still marked as incomplete - not sure if we need to fix that or not since the only other incomplete scenario is the 450 ply draw, so its pretty self evident which is which.
