### ISSUE TITLE
lc0-client compile issue 

### ISSUE THREAD

**Issue by sq5rix** [LeelaChessZero/lczero-client#88]
Hi!
I try to compile client v. 22 

I get 
./lc0_main.go:799:23: nextGame.KeepTime undefined (type client.NextGameResponse has no field or method KeepTime)

Ubuntu 18.04.2 LTS
go 1.12

Previous versions compiled ok. 
What can I do? I tried release, master and newest 3fefef28e543940d4ab13542f3bdfe05c22be62d

**Comment by madformuse** [comment]
Are you still getting this issue? It worked for me, would you have a local changed version instead of the official one?

**Comment by sq5rix** [comment]
I have official one, still the same problem.

**Comment by madformuse** [comment]
The readme says you need to 1.9 or later, could that be the problem?

**Comment by sq5rix** [comment]
go version go1.12.2 linux/amd64

**Comment by madformuse** [comment]
Sorry, I didn't read the version right. I'm no expert but seems a strange error if you have the right version! Are you experienced with Git? Don't want to be trying to tell Linus how to use Git! :) What's the output from git status?

**Comment by sq5rix** [comment]
Haha no Linus here :)
(base) tom@ferrari:~/Mega/chess/leela/lc0-client/lczero-client$ git status
HEAD detached at 5fe2f51
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	lc0
	settings.json
	update.sh

nothing added to commit but untracked files present (use "git add" to track)

**Comment by madformuse** [comment]
Could you clone repo again to different folder and see if it compiles there? Detached head seems a bit suspicious.

**Comment by sq5rix** [comment]
I did exactly that - its completely fresh. The detached means (I think) I put my files in the directory - lc0 update.sh and stettings.json

**Comment by sq5rix** [comment]
Ok, i did a fresh clone:
(base) tom@ferrari:~/Mega/chess/leela/lc0-client/lczero-client$ git status
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean

The same :( :( :(

**Comment by madformuse** [comment]
Do you get the error compiling or running?

**Comment by madformuse** [comment]
You don't get detached just from extra files. They just show as untracked files.

**Comment by madformuse** [comment]
You cloning main leelachesszero lczero-client repo?

**Comment by sq5rix** [comment]
Yes, the same error, after go build lc0_main.go

**Comment by sq5rix** [comment]
git clone https://github.com/LeelaChessZero/lczero-client.git

**Comment by madformuse** [comment]
Do you get same if you just "go build" without the file name. NextGameResponse is defined in different file. Sorry I'm a newcomer to Go so this may not be helpful.

**Comment by sq5rix** [comment]
Exactly the same :(

**Comment by madformuse** [comment]
You don't have a different version somewhere else on your go path or something wierd like that do you?

**Comment by sq5rix** [comment]
You are a genius! 
I had a stale client_http.go file in /home/tom/go/client directory 
Now it compiles without any problems
Thank you very much for your help !!

**Comment by madformuse** [comment]
Wow I'm glad glad it worked (was a stab in the dark) :). Happy coding.

**Comment by sq5rix** [comment]
Thanks again and good luck !!
