### ISSUE TITLE
Lc0 client fails if there is a space in path name

### ISSUE THREAD

**Issue by Tharagleb** [LeelaChessZero/lczero-client#9]
Client ran but would not upload games. Renamed directory from "C:\Users\xxx\Desktop\LC0 Client" to "C:\Users\xxx\Desktop\LC0Client"  (no spaces) and was able to upload games. 

May be caused by this line in lc0_main.go:

parts := strings.Split(*lc0Args, " ")

**Comment by jnewlin12345** [comment]
On Linux I see there's a bug with the 'gameready' line coming back, we split the line on spaces and there's a space in the path.  e.g.

Malformed gameready: "gameready trainingfile /tmp/foo bar/data-fnsplkvuhvkb/game_000012.gz

Can someone using windows verify that this is the same issue?

**Comment by jnewlin12345** [comment]
FWIW this bit of code seems fine:
parts := strings.Split(*lc0Args, " ")

**Comment by Tharagleb** [comment]
I have tested the code changes and it fixes the problem.
